### ISSUE TITLE
能不能考虑出个简化版的颜色选择器

### ISSUE THREAD

**Issue by rchlz** [MakerGYT/mini-color-picker#7]
不需要拖动选择颜色，直接8*8格子列出常用颜色。如果需要更多颜色，再进入现在这个界面

**Comment by rchlz** [comment]
就比如类似wps、ms word之类的颜色选择器，首先是提供标准颜色选择（大多数用户满足了），满足不了再自定义或者高级

**Comment by MakerGYT** [comment]
这种的话很容易实现的
